================================================================================
🏥 RELATÓRIO COMPLETO DO DEBATE MÉDICO
================================================================================
Data/Hora: 09/06/2026 22:07:56
Rodadas Completadas: 2
Confiança Final: 59.0%

================================================================================
📄 CONTEXTO DO CASO USADO NA ANÁLISE
================================================================================

PACIENTE
Nome: Mario Gorini
Idade: 45 anos | Homem | Nascimento 14/01/1981
Coleta mais recente: 20/03/2026
Data Análise: 09/06/2026
Laboratorio: LAB - LABORATORIO DE PATOLOGIA E CITOLOGIA APLICADA LTDA, DASA

PANORAMA GERAL
Total marcadores: 4
Laboratório → Verde 1 | Amarelo 0 | Vermelho 0 | Não disponível 3
ÓRIA funcional → Verde 0 | Amarelo 0 | Vermelho 0 | Não disponível 4

MEMÓRIA VIVA
Hábitos | Sono: — | Atividade física: — | Alimentação: — | Álcool: — | Tabaco: —
Suplementos | {'dose': None, 'nome': 'creatinina', 'frequencia': None} | {'dose': None, 'nome': 'Creatina', 'frequencia': None}
Medicações contínuas | —
Condições declaradas | —
Saúde emocional | Estresse: — | Ansiedade: — | Humor recorrente: —
Objetivos | —
Preferências de comunicação | Tom: leigo | Formato: curto | Horário preferencial: —
Outras informações relevantes | —

PONTOS POSITIVOS – MARCADORES EM ALVO FUNCIONAL
Nenhum marcador em alvo funcional disponível.

EXAMES FORA DO ALVO ÓRIA

OUTROS EXAMES REALIZADOS - VALORES ÓTIMOS NÃO DISPONÍVEL
→ Cistatina C: 0.87 mg/L (20/03/2026) | Ref lab: 0.56-0.99 mg/L
→ Creatinina Urinária: 0.88 g/L (20/03/2026) | Ref lab: —
→ Albumina Urinária: Inferior a 30 mg/L (20/03/2026) | Ref lab: —

SINAIS DE ATENÇÃO (Desvios > 50%)
→ Relação Albumina/Creatinina: Inferior a 30 mg/g (20/03/2026) | Ref lab: < 30.0 mg/g | Ótimo: 0.0-10.0 mg/g → Não disponível (Acima do Máx Ótimo > 200.0%)

================================================================================
ANÁLISE LONGITUDINAL DE EXAMES LABORATORIAIS — SECTIONS9
================================================================================
Total de marcadores monitorados: 104
Janela temporal aplicada: 10 anos
Data da análise: 09/06/2026 22:06
Renderer: sections9 | active_delta=20% | historic_gate=>12m | cluster_lookup=keywords_map.json
R1 histórico: last_age>12m vai para [7].
R2 ruído: marcador ativo com rule explícita vai para [5].
R3 cluster: cluster ativado absorve membros recentes não ruidosos.
R4 single-point: n=1 vai para [8] exceto quando absorvido por cluster ativo.
R5 trajetória: slope + persistência determinam [3]/[4].
R6 ativo isolado: last_age≤12m e |Δ|≥20% fora de cluster.
R7 estável: last_age≤12m e |Δ_base|<20% e |Δ_last|<20%.
R8 divergências: unidade/espécime/método e alertas de consistência em [9].
R9 HIST: histórico exibido até MAX_PONTOS_HIST.

LEGENDA PARA O DEBATE LLM
- role: [anchor] | [support] — papel canônico do marcador no cluster, vindo do keywords_map/allowlist.
- state: [active] | [sustained-up] | [sustained-down] | [singleton] | [stable].
- recente: [recente≤6m] | [recente 6-12m]; omitido em [7] porque toda a seção é histórica >12m.
- ref: [fora-ref] | [fora-ótimo] | [dentro-ótimo] | [sem-ref-estruturada] | [fora-ref+dentro-ótimo].
- extras: [rule=...] | [cluster=...] | [trend_note=...] | flag=surveillance_gap.
- Direção 'subindo/descendo' é matemática, não juízo clínico; melhor/pior depende do marcador, referência e contexto.
- Direção 'subindo/descendo' é matemática, não juízo clínico. Melhor/pior depende do marcador, referência e contexto.
- Tags de referência ([fora-ref]/[fora-ótimo]/[dentro-ótimo]) só aparecem quando o dado estruturado de referência/faixa ótima existe; caso contrário aparece [sem-ref-estruturada].
================================================================================

## [1] CLUSTERS COM ATIVIDADE
Sistemas fisiológicos com múltiplos marcadores recentes ativos no mesmo cluster.

[cluster=Eixo Hormonal e Tireoidiano] CLUSTER Eixo Hormonal e Tireoidiano — 4 sinais (1 âncora + 3 suporte)
[anchor][active][recente≤6m][fora-ref][trend_note=alta_longa_com_queda_curta] TSH::uui/ml | base=1.60 (median3) | last=13.70 | Δ_base=+12.10 (+756.2%) | Δ_last=-1.70 (-11.0%) | slope=+0.1121/m | persist=46% | vol=5.53 | n=14 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:14 | 2026-01-31:15 | 2026-01-17:2 | 2025-10-09:10 | 2025-05-26:2 | 2025-02-12:6 | 2024-08-07:0 | 2024-03-18:2 | 2023-11-04:0 | 2023-10-23:0
[support][active][recente≤6m][fora-ref] TESTOSTERONA TOTAL::ng/dl | base=456.80 (median3) | last=857.00 | Δ_base=+400.20 (+87.6%) | Δ_last=+406.41 (+90.2%) | slope=+3.6724/m | persist=33% | vol=261.13 | n=4 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:857.00 | 2022-10-19:450.59 | 2019-06-13:456.80 | 2018-12-17:533.95
[support][active][recente≤6m] Testosterona Biodisponível::ng/dl | base=221.60 (oldest) | last=334.20 | Δ_base=+112.60 (+50.8%) | Δ_last=+112.60 (+50.8%) | slope=+2.7308/m | persist=100% | vol=n/a | n=2 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:334.20 | 2022-10-19:221.60
[support][sustained-up][recente≤6m] T4 LIVRE::ng/dl | base=1.34 (median3) | last=1.39 | Δ_base=+0.05 (+3.7%) | Δ_last=+0.13 (+10.3%) | slope=+0.0025/m | persist=60% | vol=0.35 | n=18 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:1.39 | 2026-02-28:1.26 | 2026-01-31:0.62 | 2025-05-26:1.38 | 2024-08-07:1.27 | 2024-06-07:1.32 | 2024-03-18:1.11 | 2023-11-04:1.45 | 2023-10-23:1.29 | 2023-08-25:1.03
[support][stable][recente≤6m] DehidroepiandrosteronaSulfato - DHEA SO4::ug/dl | base=199.00 (oldest) | last=232.00 | Δ_base=+33.00 (+16.6%) | Δ_last=+33.00 (+16.6%) | slope=+0.8003/m | persist=100% | vol=n/a | n=2 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:232.00 | 2022-10-19:199.00
[cluster=Sistema Hematológico] CLUSTER Sistema Hematológico — 4 sinais (0 âncora + 4 suporte)
[support][active][recente≤6m][fora-ref] SEGMENTADOS (absoluto)::/mm³ | base=3828.50 (median3) | last=1025.00 | Δ_base=-2803.50 (-73.2%) | Δ_last=-2803.50 (-73.2%) | slope=-138.5269/m | persist=67% | vol=2078.04 | n=4 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:1025 | 2025-12-05:3828 | 2025-10-09:3940 | 2025-02-12:2655
[support][active][recente≤6m][fora-ref][trend_note=queda_longa_com_alta_curta] LEUCÓCITOS::/mm³ | base=5900.00 (median3) | last=2540.00 | Δ_base=-3360.00 (-56.9%) | Δ_last=+40.00 (+1.6%) | slope=-32.9404/m | persist=38% | vol=1528.06 | n=14 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:2540 | 2026-01-31:2500 | 2026-01-17:3250 | 2025-12-05:5890 | 2025-10-09:5890 | 2025-05-26:5880 | 2025-02-12:4500 | 2023-08-25:5880 | 2023-01-27:3250 | 2022-10-06:5890
[support][active][recente≤6m] Leucócitos::/ul | base=4700.00 (oldest) | last=6160.00 | Δ_base=+1460.00 (+31.1%) | Δ_last=+1460.00 (+31.1%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:6160 | 2026-03-09:4700
[support][sustained-down][recente≤6m] PLAQUETAS::x10³/mm³ | base=220.00 (oldest) | last=189.00 | Δ_base=-31.00 (-14.1%) | Δ_last=-30.00 (-13.7%) | slope=-2.6346/m | persist=100% | vol=20.51 | n=3 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:189 | 2025-12-05:219 | 2025-02-12:220
[support][stable][recente≤6m] MONÓCITOS (%)::% | base=8.00 (median3) | last=7.00 | Δ_base=-1.00 (-12.5%) | Δ_last=-1.00 (-12.5%) | slope=-0.0238/m | persist=50% | vol=1.71 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:7.00 | 2026-03-09:8.00 | 2026-02-28:10.00 | 2026-01-31:8.00 | 2022-10-19:8.00
[support][stable][recente≤6m] PLAQUETAS::10³/mm³ | base=213.00 (median3) | last=187.00 | Δ_base=-26.00 (-12.2%) | Δ_last=-26.00 (-12.2%) | slope=-0.7736/m | persist=57% | vol=12.35 | n=8 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:187 | 2026-01-17:213 | 2025-10-09:219 | 2025-05-26:222 | 2023-08-25:222 | 2023-01-27:213 | 2022-10-19:205 | 2022-10-06:219
[support][stable][recente≤6m] SEGMENTADOS (%)::% | base=60.00 (median3) | last=65.60 | Δ_base=+5.60 (+9.3%) | Δ_last=+5.60 (+9.3%) | slope=+0.1159/m | persist=50% | vol=9.46 | n=17 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:65.60 | 2026-03-09:60.00 | 2026-02-28:40.00 | 2026-01-31:41.00 | 2026-01-17:65.00 | 2025-12-05:65.00 | 2025-10-09:65.00 | 2025-05-26:67.00 | 2025-02-12:59.00 | 2023-08-25:67.00
[support][stable][recente≤6m][trend_note=alta_longa_com_queda_curta] VMP::fl | base=10.80 (median3) | last=11.60 | Δ_base=+0.80 (+7.4%) | Δ_last=-0.50 (-4.1%) | slope=+0.0071/m | persist=50% | vol=1.38 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:11.60 | 2026-03-09:12.10 | 2026-02-28:10.80 | 2026-01-31:9.70 | 2022-10-19:11.30
[support][stable][recente≤6m] RDW::% | base=13.50 (median3) | last=12.60 | Δ_base=-0.90 (-6.7%) | Δ_last=-0.50 (-3.8%) | slope=+0.0143/m | persist=50% | vol=3.63 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:12.60 | 2026-03-09:13.10 | 2026-02-28:17.60 | 2026-01-31:13.50 | 2022-10-19:12.00
[support][stable][recente≤6m][trend_note=alta_longa_com_queda_curta] HEMATOCRITO::% | base=44.10 (median3) | last=45.80 | Δ_base=+1.70 (+3.9%) | Δ_last=-2.70 (-5.6%) | slope=+0.0130/m | persist=44% | vol=4.86 | n=17 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:45.80 | 2026-03-09:48.50 | 2026-02-28:38.80 | 2026-01-31:36.10 | 2026-01-17:36.70 | 2025-12-05:38.50 | 2025-10-09:38.50 | 2025-05-26:38.90 | 2025-02-12:40.60 | 2023-08-25:38.90
[support][stable][recente≤6m][fora-ref] CHCM::g/dl | base=34.10 (median3) | last=35.80 | Δ_base=+1.70 (+5.0%) | Δ_last=+1.20 (+3.5%) | slope=-0.0214/m | persist=50% | vol=2.41 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:35.80 | 2026-03-09:34.60 | 2026-02-28:32.20 | 2026-01-31:34.10 | 2022-10-19:36.70
[anchor][stable][recente≤6m][trend_note=alta_longa_com_queda_curta] HEMOGLOBINA::g/dl | base=15.80 (median3) | last=16.40 | Δ_base=+0.60 (+3.8%) | Δ_last=-0.40 (-2.4%) | slope=+0.0040/m | persist=44% | vol=1.98 | n=17 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:16.40 | 2026-03-09:16.80 | 2026-02-28:12.50 | 2026-01-31:12.30 | 2026-01-17:12.40 | 2025-12-05:13.60 | 2025-10-09:13.60 | 2025-05-26:13.00 | 2025-02-12:13.60 | 2023-08-25:13.00
[support][stable][recente≤6m] VCM::fl | base=91.20 (median3) | last=88.60 | Δ_base=-2.60 (-2.9%) | Δ_last=-0.80 (-0.9%) | slope=+0.0904/m | persist=50% | vol=8.34 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:88.60 | 2026-03-09:89.40 | 2026-02-28:99.50 | 2026-01-31:91.20 | 2022-10-19:84.80
[support][stable][recente≤6m] HCM::pg | base=31.10 (median3) | last=31.70 | Δ_base=+0.60 (+1.9%) | Δ_last=+0.80 (+2.6%) | slope=+0.0143/m | persist=50% | vol=1.00 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:31.70 | 2026-03-09:30.90 | 2026-02-28:32.10 | 2026-01-31:31.10 | 2022-10-19:31.10
[support][stable][recente≤6m] Contagem de Plaquetas::/ul | base=175000.00 (oldest) | last=171000.00 | Δ_base=-4000.00 (-2.3%) | Δ_last=-4000.00 (-2.3%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:171000 | 2026-03-09:175000
[support][stable][recente≤6m] BASTONETES (absoluto)::/mm³ | base=0.00 (oldest) | last=0.00 | Δ_base=n/a (n/a) | Δ_last=n/a (n/a) | slope=+0.0000/m | persist=100% | vol=0.00 | n=3 | last_date=2025-12-05 | gap=6m | HIST: 2025-12-05:0 | 2025-05-26:0 | 2025-02-12:0
[anchor][stable][recente≤6m] Hemoglobina Glicada - HbA1c::% | base=5.50 (oldest) | last=5.50 | Δ_base=+0.00 (+0.0%) | Δ_last=+0.00 (+0.0%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:5.50 | 2026-03-09:5.50
[cluster=Saúde Renal e Ácido Úrico] CLUSTER Saúde Renal e Ácido Úrico — 2 sinais (1 âncora + 1 suporte)
[anchor][active][recente≤6m][fora-ref] CREATININA::mg/dl | base=1.16 (median3) | last=1.64 | Δ_base=+0.48 (+41.4%) | Δ_last=+0.70 (+74.5%) | slope=+0.0048/m | persist=47% | vol=0.21 | n=18 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:1.64 | 2026-02-28:0.94 | 2026-01-31:0.96 | 2026-01-17:0.97 | 2025-10-09:0.82 | 2025-02-12:0.83 | 2024-03-18:0.71 | 2023-08-25:0.68 | 2023-03-28:0.70 | 2023-01-27:0.80
[support][active][recente≤6m] UREIA::mg/dl | base=31.00 (median3) | last=45.00 | Δ_base=+14.00 (+45.2%) | Δ_last=+11.00 (+32.4%) | slope=+0.1914/m | persist=100% | vol=4.16 | n=4 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:45.00 | 2019-06-13:34.00 | 2018-12-17:31.00 | 2018-01-12:26.00
[anchor][stable][recente≤6m] ESTIMATIVA DA TAXA DE FILTRAÇÃO GLOMERULAR::ml/min/1,73m² | base=62.00 (oldest) | last=52.00 | Δ_base=-10.00 (-16.1%) | Δ_last=-10.00 (-16.1%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:52.00 | 2026-02-28:62.00
[cluster=Vitaminas, Minerais e Cofatores] CLUSTER Vitaminas, Minerais e Cofatores — 2 sinais (0 âncora + 2 suporte)
[support][active][recente≤6m] VITAMINA D::ng/ml | base=33.00 (oldest) | last=68.00 | Δ_base=+35.00 (+106.1%) | Δ_last=+15.00 (+28.3%) | slope=+0.3979/m | persist=100% | vol=3.54 | n=3 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:68 | 2019-06-13:53 | 2018-12-17:33
[support][active][recente≤6m] VITAMINA B12::pg/ml | base=392.00 (median3) | last=720.00 | Δ_base=+328.00 (+83.7%) | Δ_last=+143.00 (+24.8%) | slope=+5.3060/m | persist=60% | vol=95.21 | n=6 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:720 | 2026-03-09:577 | 2022-10-19:384 | 2020-08-08:392 | 2019-06-13:400 | 2018-12-17:249
[support][stable][recente≤6m] MAGNÉSIO::mg/dl | base=2.00 (median3) | last=2.20 | Δ_base=+0.20 (+10.0%) | Δ_last=+0.00 (+0.0%) | slope=+0.0031/m | persist=40% | vol=0.11 | n=11 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:2.20 | 2026-01-31:2.20 | 2026-01-17:2.20 | 2023-08-25:2.20 | 2022-04-08:2.10 | 2022-03-03:2.30 | 2021-11-11:2.20 | 2021-04-05:2.00 | 2021-03-14:1.90 | 2021-02-10:2.00
[support][stable][recente≤6m] POTÁSSIO::meq/l | base=4.60 (median3) | last=5.00 | Δ_base=+0.40 (+8.7%) | Δ_last=+0.10 (+2.0%) | slope=+0.0103/m | persist=55% | vol=0.50 | n=12 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:5.00 | 2026-01-31:4.90 | 2026-01-17:4.70 | 2023-08-25:5.30 | 2023-01-27:4.50 | 2022-10-06:4.50 | 2022-07-25:5.10 | 2022-05-28:4.60 | 2022-04-08:4.10 | 2022-03-03:4.60
[support][stable][recente≤6m] CLORO::meq/l | base=105.00 (median3) | last=102.00 | Δ_base=-3.00 (-2.9%) | Δ_last=+0.00 (+0.0%) | slope=-0.0200/m | persist=33% | vol=3.27 | n=11 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:102.00 | 2026-01-31:102.00 | 2026-01-17:99.00 | 2023-01-27:105.00 | 2022-07-25:107.00 | 2020-05-04:105.00 | 2017-12-18:104.00
[support][stable][recente≤6m] SÓDIO::meq/l | base=137.00 (median3) | last=140.00 | Δ_base=+3.00 (+2.2%) | Δ_last=+3.00 (+2.2%) | slope=+0.0228/m | persist=45% | vol=2.09 | n=12 | last_date=2026-02-28 | gap=3m | HIST: 2026-02-28:140.00 | 2026-01-31:137.00 | 2026-01-17:137.00 | 2023-08-25:138.00 | 2023-01-27:139.00 | 2022-10-06:136.00 | 2022-07-25:139.00 | 2022-05-28:138.00 | 2022-04-08:138.00 | 2022-03-03:137.00
[cluster=Risco Cardiovascular, Inflamação e Perfil Lipídico] CLUSTER Risco Cardiovascular, Inflamação e Perfil Lipídico — 1 sinais (0 âncora + 1 suporte)
[support][active][recente≤6m] FERRITINA::ng/ml | base=185.70 (median3) | last=329.00 | Δ_base=+143.30 (+77.2%) | Δ_last=+106.40 (+47.8%) | slope=+1.1571/m | persist=50% | vol=75.95 | n=11 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:329 | 2022-10-19:223 | 2020-08-08:124 | 2019-06-13:166 | 2018-12-17:110 | 2018-01-12:186 | 2016-11-30:198
[cluster=Saúde Hepática e Detoxificação] CLUSTER Saúde Hepática e Detoxificação — 0 sinais (0 âncora + 0 suporte)
[anchor][stable][recente≤6m] GAMA GLUTAMIL TRANSFERASE::u/l | base=14.00 (median3) | last=13.00 | Δ_base=-1.00 (-7.1%) | Δ_last=-2.00 (-13.3%) | slope=-0.0101/m | persist=50% | vol=4.79 | n=8 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:13.00 | 2022-10-19:15.00 | 2019-06-13:10.00 | 2018-12-17:16.00 | 2018-01-12:14.00

## [2] ATIVOS ISOLADOS
Marcadores recentes com |Δ|≥20% que não foram absorvidos por cluster ativado.

Sem marcadores.

## [3] TRAJETÓRIA SUSTENTADA — SUBINDO
Slope > 0, persistência ≥ 60%, n ≥ 3. Direção numérica, não juízo clínico.

Sem marcadores.

## [4] TRAJETÓRIA SUSTENTADA — DESCENDO
Slope < 0, persistência ≥ 60%, n ≥ 3. Direção numérica, não juízo clínico.

[support][sustained-down][recente≤6m] ALUMÍNIO::ug/l | base=2.00 (median3) | last=1.76 | Δ_base=-0.24 (-12.0%) | Δ_last=-0.24 (-12.0%) | slope=-0.0027/m | persist=67% | vol=1.61 | n=4 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:1.76 | 2022-10-19:2.00 | 2019-06-13:3.60 | 2018-12-17:2.00
[support][sustained-down][recente≤6m] Eritrócitos::10⁶/ul | base=5.27 (median3) | last=5.17 | Δ_base=-0.10 (-1.9%) | Δ_last=-0.26 (-4.8%) | slope=-0.0024/m | persist=67% | vol=1.46 | n=4 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:5 | 2026-03-09:5 | 2026-02-28:4 | 2022-10-19:5

## [5] RUÍDO ESTATÍSTICO
Marcadores rebaixados por regra determinística de ruído (rule=...). Permanecem visíveis ao debate.

[anchor][active][rule=acute_swing_normalized][cluster=Saúde Hepática e Detoxificação][trend_note=queda_longa_com_alta_curta] TRANSAMINASE PIRÚVICA TGP (ALT)::u/l | base=22.00 (median3) | last=16.00 | Δ_base=-6.00 (-27.3%) | Δ_last=+1.00 (+6.7%) | slope=-0.0604/m | persist=43% | vol=4.22 | n=15 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:16.00 | 2026-02-28:15.00 | 2026-01-31:13.00 | 2026-01-17:15.00 | 2025-10-09:15.00 | 2024-03-18:17.00 | 2023-08-25:16.00 | 2023-03-28:27.00 | 2023-01-27:18.00 | 2022-11-29:18.00
[anchor][active][rule=acute_swing_normalized][cluster=Saúde Hepática e Detoxificação] TRANSAMINASE OXALACÉTICA TGO (AST)::u/l | base=28.00 (median3) | last=32.00 | Δ_base=+4.00 (+14.3%) | Δ_last=+9.00 (+39.1%) | slope=+0.0680/m | persist=64% | vol=5.35 | n=12 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:32.00 | 2026-02-28:23.00 | 2026-01-31:20.00 | 2026-01-17:20.00 | 2025-10-09:31.00 | 2024-03-18:27.00 | 2023-08-25:26.00 | 2023-03-28:32.00 | 2023-01-27:29.00 | 2022-11-29:28.00
[support][active][rule=acute_swing_normalized][cluster=Sistema Hematológico] BASÓFILOS (%)::% | base=1.00 (median3) | last=0.60 | Δ_base=-0.40 (-40.0%) | Δ_last=n/a (n/a) | slope=+0.0143/m | persist=25% | vol=1.45 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:0.60 | 2026-03-09:0.00 | 2026-02-28:2.00 | 2026-01-31:1.00 | 2022-10-19:0.00
[support][active][rule=acute_swing_normalized][cluster=Sistema Hematológico][trend_note=alta_longa_com_queda_curta] EOSINÓFILOS (%)::% | base=1.00 (median3) | last=2.40 | Δ_base=+1.40 (+140.0%) | Δ_last=-2.60 (-52.0%) | slope=+0.0095/m | persist=25% | vol=2.81 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:2.40 | 2026-03-09:5.00 | 2026-02-28:1.00 | 2026-01-31:1.00 | 2022-10-19:2.00
[support][active][rule=acute_swing_normalized][cluster=Risco Cardiovascular, Inflamação e Perfil Lipídico] HOMOCISTEÍNA::umol/l | base=33.00 (median3) | last=7.40 | Δ_base=-25.60 (-77.6%) | Δ_last=-9.50 (-56.2%) | slope=-0.1533/m | persist=71% | vol=12.80 | n=9 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:7.40 | 2022-10-19:16.90 | 2020-08-08:14.60 | 2019-07-31:18.40 | 2019-06-13:31.70 | 2018-12-17:33.00 | 2018-01-12:47.60 | 2016-11-30:24.70
[support][active][rule=acute_swing_normalized][cluster=Sistema Hematológico] LINFÓCITOS (%)::% | base=47.00 (median3) | last=24.40 | Δ_base=-22.60 (-48.1%) | Δ_last=-2.60 (-9.6%) | slope=-0.0856/m | persist=75% | vol=16.82 | n=5 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:24.40 | 2026-03-09:27.00 | 2026-02-28:47.00 | 2026-01-31:49.00 | 2022-10-19:28.00

## [6] ESTÁVEL
last_age ≤ 12m, |Δ_base| < 20% e |Δ_last| < 20%.

[support][stable][recente≤6m][cluster=Metabolismo Glicêmico e Insulinêmico] Glicose::mg/dl | base=86.00 (oldest) | last=92.00 | Δ_base=+6.00 (+7.0%) | Δ_last=+6.00 (+7.0%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:92.00 | 2026-03-09:86.00
[support][stable][recente≤6m] Cistatina C::mg/l | base=0.87 (oldest) | last=0.83 | Δ_base=-0.04 (-4.6%) | Δ_last=-0.04 (-4.6%) | slope=n/a | persist=100% | vol=n/a | n=2 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:0.83 | 2026-03-20:0.87

## [7] HISTÓRICO
last_age > 12m. Agrupado por cluster; flag=surveillance_gap quando gap > threshold do sistema.

[cluster=Eixo Hormonal e Tireoidiano]
[support][stable] T3 LIVRE::pg/ml | base=3.30 (oldest) | last=3.30 | Δ_base=+0.00 (+0.0%) | Δ_last=+0.00 (+0.0%) | slope=+0.0000/m | persist=100% | vol=n/a | n=2 | last_date=2019-06-13 | gap=85m | flag=surveillance_gap | HIST: 2019-06-13:3 | 2018-12-17:3
[support][stable] TESTOSTERONA LIVRE::pg/ml | base=111.43 (oldest) | last=88.93 | Δ_base=-22.50 (-20.2%) | Δ_last=-22.50 (-20.2%) | slope=-3.7921/m | persist=100% | vol=n/a | n=2 | last_date=2019-06-13 | gap=85m | flag=surveillance_gap | HIST: 2019-06-13:89 | 2018-12-17:111
[support][singleton] DEHIDROEPIANDROSTERONA (DHEA)::ng/ml | base=2.76 (oldest) | last=2.76 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:3
[support][singleton] T3 REVERSO::ng/ml | base=0.68 (oldest) | last=0.68 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:1
[support][sustained-up] T4 HORMÔNIO TIROXINA::mcg/dl | base=7.70 (oldest) | last=8.60 | Δ_base=+0.90 (+11.7%) | Δ_last=+0.60 (+7.5%) | slope=+0.0193/m | persist=100% | vol=0.21 | n=3 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:8.60 | 2019-06-13:8.00 | 2018-12-17:7.70
[support][singleton] TESTOSTERONA LIVRE::nmol/l | base=327.00 (oldest) | last=327.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:327.00
[cluster=Marcadores Tumorais e de Alta Especificidade]
[support][stable][trend_note=queda_longa_com_alta_curta] CA 125::u/ml | base=8.43 (median3) | last=7.84 | Δ_base=-0.59 (-7.0%) | Δ_last=+0.45 (+6.1%) | slope=+0.0117/m | persist=25% | vol=1.15 | n=5 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:8 | 2020-08-08:7 | 2019-06-13:9 | 2018-01-12:8 | 2016-11-30:7
[support][singleton] PSA LIVRE::ng/ml | base=0.15 (oldest) | last=0.15 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:0
[support][singleton] RELAÇÃO PSA LIVRE/PSA TOTAL::% | base=36.60 (oldest) | last=36.60 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:36.60
[support][sustained-up] PSA TOTAL::ng/ml | base=0.27 (median3) | last=0.41 | Δ_base=+0.14 (+51.9%) | Δ_last=+0.09 (+28.1%) | slope=+0.0025/m | persist=100% | vol=0.03 | n=5 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:0 | 2020-08-08:0 | 2019-06-13:0 | 2018-01-12:0 | 2016-11-30:0
[cluster=Risco Cardiovascular, Inflamação e Perfil Lipídico]
[support][stable] PCR ULTRASENSÍVEL::mg/l | base=0.96 (oldest) | last=1.90 | Δ_base=+0.94 (+97.9%) | Δ_last=+0.94 (+97.9%) | slope=+0.1584/m | persist=100% | vol=n/a | n=2 | last_date=2019-06-13 | gap=85m | flag=surveillance_gap | HIST: 2019-06-13:1.90 | 2018-12-17:0.96
[support][stable] COLESTEROL HDL::mg/dl | base=47.00 (median3) | last=50.00 | Δ_base=+3.00 (+6.4%) | Δ_last=+0.00 (+0.0%) | slope=+0.0558/m | persist=50% | vol=6.98 | n=6 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:50.00 | 2019-06-13:50.00 | 2018-12-17:57.00 | 2018-01-12:47.00 | 2016-11-30:46.00
[support][stable] COLESTEROL LDL::mg/dl | base=117.00 (oldest) | last=136.00 | Δ_base=+19.00 (+16.2%) | Δ_last=+25.00 (+22.5%) | slope=+0.4066/m | persist=50% | vol=21.92 | n=3 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:136.00 | 2019-06-13:111.00 | 2018-12-17:117.00
[support][stable] COLESTEROL NÃO HDL::mg/dl | base=139.00 (median3) | last=154.00 | Δ_base=+15.00 (+10.8%) | Δ_last=+30.00 (+24.2%) | slope=+0.2094/m | persist=50% | vol=21.55 | n=6 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:154.00 | 2019-06-13:124.00 | 2018-12-17:125.00 | 2018-01-12:147.00 | 2016-11-30:139.00
[support][sustained-down] TRIGLICERÍDEOS::mg/dl | base=133.00 (median3) | last=106.00 | Δ_base=-27.00 (-20.3%) | Δ_last=-6.00 (-5.4%) | slope=-1.2145/m | persist=75% | vol=34.59 | n=6 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:106.00 | 2019-06-13:112.00 | 2018-12-17:94.00 | 2018-01-12:133.00 | 2016-11-30:193.00
[cluster=Sistema Hematológico]
[support][stable] BASTONETES (%)::% | base=0.00 (median3) | last=0.00 | Δ_base=n/a (n/a) | Δ_last=n/a (n/a) | slope=+0.0000/m | persist=100% | vol=0.00 | n=4 | last_date=2020-08-08 | gap=71m | flag=surveillance_gap | HIST: 2020-08-08:0.00 | 2019-06-13:0.00 | 2018-12-17:0.00 | 2018-01-12:0.00
[support][sustained-down] PLAQUETAS::x10³/ul | base=198.00 (median3) | last=202.00 | Δ_base=+4.00 (+2.0%) | Δ_last=+4.00 (+2.0%) | slope=-0.4153/m | persist=67% | vol=23.63 | n=4 | last_date=2020-08-08 | gap=71m | flag=surveillance_gap | HIST: 2020-08-08:202 | 2019-06-13:198 | 2018-12-17:184 | 2018-01-12:215
[support][singleton] SEGMENTADOS (absoluto)::/mm3 | base=3348.00 (oldest) | last=3348.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:3348
[support][singleton] LEUCOCITOS::/mm3 | base=5400.00 (oldest) | last=5400.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:5400
[cluster=Vitaminas, Minerais e Cofatores]
[support][stable] CÁLCIO::mg/dl | base=9.40 (oldest) | last=9.10 | Δ_base=-0.30 (-3.2%) | Δ_last=-0.30 (-3.2%) | slope=-0.0506/m | persist=100% | vol=n/a | n=2 | last_date=2019-06-13 | gap=85m | flag=surveillance_gap | HIST: 2019-06-13:9.10 | 2018-12-17:9.40
[support][sustained-down] ÁCIDO FÓLICO::ng/ml | base=13.63 (median3) | last=8.43 | Δ_base=-5.20 (-38.2%) | Δ_last=-5.20 (-38.2%) | slope=-0.1489/m | persist=67% | vol=2.80 | n=4 | last_date=2022-10-19 | gap=44m | flag=surveillance_gap | HIST: 2022-10-19:8 | 2020-08-08:14 | 2019-06-13:13 | 2018-12-17:15
[cluster=[unclustered]]
[support][singleton] BASOFILOS (absoluto)::/mm3 | base=0.00 (oldest) | last=0.00 | Δ_base=n/a (n/a) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | HIST: 2022-10-19:0
[support][sustained-down] CA 19/9::u/ml | base=4.69 (median3) | last=4.87 | Δ_base=+0.18 (+3.8%) | Δ_last=+0.11 (+2.3%) | slope=-0.0145/m | persist=75% | vol=0.75 | n=5 | last_date=2022-10-19 | gap=44m | HIST: 2022-10-19:5 | 2020-08-08:5 | 2019-06-13:5 | 2018-01-12:5 | 2016-11-30:6
[support][singleton] EOSINOFILOS (absoluto)::/mm3 | base=108.00 (oldest) | last=108.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | HIST: 2022-10-19:108
[support][singleton] LINFOCITOS (absoluto)::/mm3 | base=1512.00 (oldest) | last=1512.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | HIST: 2022-10-19:1512
[support][singleton] MONOCITOS (absoluto)::/mm3 | base=432.00 (oldest) | last=432.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2022-10-19 | gap=44m | HIST: 2022-10-19:432

## [8] SINGLE-POINT
n=1 na janela atual.

### RECENTES SEM HISTÓRICO PRÉVIO (origem: histórico clínico, ≤6m, n=1)
[support][singleton][cluster=Eixo Hormonal e Tireoidiano] Hormônio Folículo Estimulante -FSH::mui/ml | base=4.80 (oldest) | last=4.80 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:5
[support][singleton][cluster=Eixo Hormonal e Tireoidiano] Hormônio Luteinizante (LH)::mui/ml | base=11.80 (oldest) | last=11.80 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:12
[support][singleton] Peptídeo C::ng/ml | base=1.50 (oldest) | last=1.50 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:2
[support][singleton][cluster=Eixo Hormonal e Tireoidiano] T3 Total (Triiodotironina)::ng/dl | base=110.00 (oldest) | last=110.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-04-02 | gap=2m | HIST: 2026-04-02:110.00
[support][singleton] Cistatina C::mg/l | base=0.87 (oldest) | last=0.87 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-20 | gap=2m | HIST: 2026-03-20:0.87
[support][singleton][cluster=Saúde Renal e Ácido Úrico] Creatinina Urinária::g/l | base=0.88 (oldest) | last=0.88 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-20 | gap=2m | HIST: 2026-03-20:0.88
[support][singleton][cluster=Saúde Hepática e Detoxificação] Albumina Urinária::mg/l | base=3.00 (oldest) | last=3.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-20 | gap=2m | HIST: 2026-03-20:3.00
[support][singleton][cluster=Saúde Hepática e Detoxificação] Fosfatase Alcalina::u/l | base=60.00 (oldest) | last=60.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:60.00
[support][singleton][cluster=Sistema Hematológico] Basófilos (absoluto)::/ul | base=0.00 (oldest) | last=0.00 | Δ_base=n/a (n/a) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:0
[support][singleton][cluster=Saúde Hepática e Detoxificação] Bilirrubina Direta::mg/dl | base=0.24 (oldest) | last=0.24 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:0.24
[support][singleton][cluster=Saúde Hepática e Detoxificação] Bilirrubina Indireta::mg/dl | base=0.54 (oldest) | last=0.54 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:0.54
[support][singleton][cluster=Saúde Hepática e Detoxificação] Bilirrubina Total::mg/dl | base=0.78 (oldest) | last=0.78 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:0.78
[support][singleton][cluster=Eixo Neuroendócrino e Adaptativo] Cortisol - Noite::ug/dl | base=18.60 (oldest) | last=18.60 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:18.60
[anchor][singleton][cluster=Risco Cardiovascular, Inflamação e Perfil Lipídico] Proteína C Reativa(PCR)::mg/dl | base=0.10 (oldest) | last=0.10 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:0.10
[support][singleton][cluster=Sistema Hematológico] Eosinófilos (absoluto)::/ul | base=235.00 (oldest) | last=235.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:235
[anchor][singleton][cluster=Eixo Hormonal e Tireoidiano] Estradiol::pg/ml | base=28.40 (oldest) | last=28.40 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:28
[support][singleton][cluster=Metabolismo Glicêmico e Insulinêmico] Insulina::uui/ml | base=1.50 (oldest) | last=1.50 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:2
[support][singleton][cluster=Vitaminas, Minerais e Cofatores] Ferro (Ferrozine sem desproteinização)::ug/dl | base=93.80 (oldest) | last=93.80 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:93.80
[support][singleton][cluster=Sistema Hematológico] Linfócitos (absoluto)::/ul | base=1269.00 (oldest) | last=1269.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:1269
[support][singleton][cluster=Sistema Hematológico] Monócitos (absoluto)::/ul | base=376.00 (oldest) | last=376.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:376
[support][singleton][cluster=Sistema Hematológico] Segmentados (absoluto)::/ul | base=2820.00 (oldest) | last=2820.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:2820
[support][singleton][cluster=Eixo Hormonal e Tireoidiano] Globulina Ligadora deHormonios Sexuais::nmol/l | base=54.80 (oldest) | last=54.80 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:54.80
[support][singleton][cluster=Eixo Hormonal e Tireoidiano] Testosterona Livre::ng/dl | base=14.26 (oldest) | last=14.26 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:14.26
[support][singleton][cluster=Vitaminas, Minerais e Cofatores] Capacidade Total de Fixação do Ferro::ug/dl | base=248.00 (oldest) | last=248.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:248.00
[support][singleton][cluster=Vitaminas, Minerais e Cofatores] Índice de Saturação da Transferrina::% | base=37.90 (oldest) | last=37.90 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:37.90
[support][singleton][cluster=Vitaminas, Minerais e Cofatores] Capacidade de Fixação Latente do Ferro::ug/dl | base=154.00 (oldest) | last=154.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:154.00
[support][singleton][cluster=Vitaminas, Minerais e Cofatores] Zinco Sanguineo::ug/dl | base=73.70 (oldest) | last=73.70 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-03-09 | gap=3m | HIST: 2026-03-09:73.70
[support][singleton][cluster=Sistema Hematológico] BASÓFILOS (absoluto)::/mm³ | base=25.00 (oldest) | last=25.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:25
[support][singleton][cluster=Sistema Hematológico] EOSINÓFILOS (absoluto)::/mm³ | base=25.00 (oldest) | last=25.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:25
[support][singleton][cluster=Saúde Renal e Ácido Úrico] ESTIMATIVA DA TAXA DE FILTRAÇÃO GLOMERULAR::ml/min/1.73m2 | base=61.00 (oldest) | last=61.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:61.00
[support][singleton][cluster=Sistema Hematológico] LINFÓCITOS (absoluto)::/mm³ | base=1225.00 (oldest) | last=1225.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:1225
[support][singleton][cluster=Sistema Hematológico] MONÓCITOS (absoluto)::/mm³ | base=200.00 (oldest) | last=200.00 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:200
[support][singleton][cluster=Sistema Hematológico] HEMÁCIAS::10⁶/mm³ | base=3.96 (oldest) | last=3.96 | Δ_base=+0.00 (+0.0%) | Δ_last=n/a (n/a) | slope=n/a | persist=n/a | vol=n/a | n=1 | last_date=2026-01-31 | gap=4m | HIST: 2026-01-31:4


> Nota: 2 singletons recentes do lote atual foram suprimidos desta seção (já exibidos na camada recente do contexto).

## [9] DIVERGÊNCIAS DE CANONICALIZAÇÃO
Inconsistências de unidade, espécime, método ou horário que comprometem comparabilidade.

Sem divergências de canonicalização detectadas neste render.

================================================================================
SUMÁRIO ESTRUTURAL
[1]=33 | [2]=0 | [3]=0 | [4]=2 | [5]=6 | [6]=2 | [7]=26 | [8]=35 | [9]=0
================================================================================


================================================================================
📋 HISTÓRICO DAS RODADAS
================================================================================

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 1 - Dr. Causa-Raiz
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 36,325 in / 2,052 out
Custo estimado: US$ 0.003340

<start>

PASSO 0 — MAPA COMBINATÓRIO

1. **Cluster: Eixo Tireoidiano**
   - Peso sistêmico: ALTO
   - Capacidade organizadora: MÉDIA (impacta metabolismo basal e regulação hormonal)
   - Marcadores ÂNCORA: TSH, T4 Livre
   - Marcadores de SUPORTE: T3 Total, T3 Livre
   - Mecanismo: Disfunção do eixo hipotálamo-hipófise-tireoide com elevação recente de TSH, sugerindo necessidade de avaliação de tireoidite ou resistência periférica.

2. **Cluster: Saúde Renal**
   - Peso sistêmico: ALTO
   - Capacidade organizadora: BAIXA (indicador de função de órgão vital)
   - Marcadores ÂNCORA: Creatinina, eGFR (TFGe), Cistatina C
   - Marcadores de SUPORTE: Ureia
   - Mecanismo: Declínio da função de filtração glomerular com elevação de creatinina e redução de TFGe, exigindo exclusão de causas transitórias.

3. **Cluster: Eixo Androgênico**
   - Peso sistêmico: MÉDIO
   - Capacidade organizadora: BAIXA
   - Marcadores ÂNCORA: Testosterona Total, Testosterona Livre
   - Marcadores de SUPORTE: DHEA-S, SHBG
   - Mecanismo: Aumento expressivo da testosterona total, possivelmente relacionado ao uso de suplementação (Creatina/outros) ou modulação exógena.

<causa-raiz>
<primaria>
  <nome_tecnico>Disfunção do Eixo Tireoidiano e Declínio da Função Renal</nome_tecnico>
  <nome_paciente>Equilíbrio da Tireoide e Saúde dos Rins</nome_paciente>
  <descricao>O paciente apresenta uma elevação significativa do TSH (13.70 uui/ml) e um declínio concomitante da função renal (Creatinina 1.64 mg/dl; TFGe 52 ml/min/1,73m²). A simultaneidade dessas alterações em órgãos vitais exige investigação imediata para descartar patologias sistêmicas ou efeitos colaterais de substâncias.</descricao>
  <etiologia_hipotetica>
    Etiologia não determinável com os dados atuais. A elevação do TSH pode ser tireoidite autoimune ou estresse agudo. O declínio renal pode ser secundário a desidratação, uso de suplementos (Creatina), ou nefropatia incipiente. Exames em <dados_faltantes_criticos>.
  </etiologia_hipotetica>
  <revalidacao status="exigida">Revalidação imediata necessária para confirmar se as alterações são persistentes ou artefatos de coleta/suplementação.</revalidacao>
  <baseline_ausente>Anti-TPO, Anti-Tireoglobulina, Urina tipo I, Relação Albumina/Creatinina (confirmar valor exato).</baseline_ausente>
  <diferenciais>Tireoidite de Hashimoto vs. Hipotireoidismo subclínico; Nefropatia primária vs. Injúria renal aguda por suplementação.</diferenciais>
  <lastro_causa_raiz>
    <marcadores_ancora>TSH | 13.70 | uui/ml | 28/02/2026 | 0.4-4.0 | 1.0-2.5 | Âncora Tireoide</marcadores_ancora>
    <marcadores_ancora>CREATININA | 1.64 | mg/dl | 09/03/2026 | 0.7-1.3 | 0.7-0.9 | Âncora Renal</marcadores_ancora>
    <marcadores_suporte>TFGe | 52 | ml/min/1,73m² | 09/03/2026 | >60 | >90 | Suporte Renal</marcadores_suporte>
    <mecanismo_vinculado>Aumento de TSH sugere hipofunção tireoidiana; aumento de creatinina sugere redução da taxa de filtração renal.</mecanismo_vinculado>
    <origem_do_lastro>critério_laboratorial_objetivo</origem_do_lastro>
    <evidencia_externa tipo="nao_disponivel" aplicabilidade="nao">nao disponivel</evidencia_externa>
    <hipoteses_concorrentes>Uso de creatina interferindo na creatinina sérica; Tireoidite autoimune.</hipoteses_concorrentes>
    <teto_de_certeza_permitido>provavel</teto_de_certeza_permitido>
  </lastro_causa_raiz>
  <nivel_certeza>provável</nivel_certeza>
</primaria>

<cobertura_clusters>
  <cluster_principal>Eixo Hormonal e Tireoidiano</cluster_principal>
  <cluster_secundario>Saúde Renal e Ácido Úrico</cluster_secundario>
  <descartados_grupo>Sistema Hematológico (alterações pontuais sem âncora de dano estrutural).</descartados_grupo>
</cobertura_clusters>
</causa-raiz>

<otimizacao>
<suplementacao_uso_livre>
- Suplemento: Creatina — "deve ser avaliado" (suspender temporariamente para reteste de creatinina).
- Alertas/contraindicações: A creatina pode elevar falsamente a creatinina sérica.
- Monitorar: Creatinina, TSH, T4 Livre em 4 semanas.
</suplementacao_uso_livre>
</otimizacao>

<risco_preditivo>
- Trajetória observada: Declínio da função renal (TFGe 52) e elevação de TSH (13.7).
- Modificabilidade: Parcialmente reversível se a causa for suplementação ou tireoidite tratável.
- Condição de reversão: Suspensão de suplementos, investigação de autoimunidade tireoidiana e hidratação adequada.
- Limite da evidência: Falta de urina tipo I e anticorpos tireoidianos.
- Marcadores de reavaliação: TSH, T4L, Creatinina, Urina tipo I, Anti-TPO.
</risco_preditivo>

<dados_resumo>
- Total exame em exames_agrupados: 104
- Total situacao: amarelo (0) | vermelho (0)
- Total situacao_otima: vermelho (0) | amarelo (0) | verde (0)
</dados_resumo>

<sinais_de_atencao_fornecidos>
Relação Albumina/Creatinina: Inferior a 30 mg/g (20/03/2026)
</sinais_de_atencao_fornecidos>

<sinais_de_atencao_inferidos>
- Convergência de TSH elevado e T4L estável (hipotireoidismo em curso);
- Dissonância entre creatinina elevada e uso de creatina (possível artefato);
- Aumento expressivo de Testosterona Total (857 ng/dl) frente ao histórico.
</sinais_de_atencao_inferidos>

<dados_faltantes_criticos>
- Anti-TPO e Anti-Tireoglobulina (investigar autoimunidade);
- Urina tipo I (investigar proteinúria/hematúria);
- Relação Albumina/Creatinina (valor quantitativo preciso);
- Suspensão de creatina por 15 dias antes de novo teste renal.
</dados_faltantes_criticos>

<analise_de_padroes_latentes>
<diretriz_executiva>
- Padrão 1: Elevação de TSH com T4L mantido (Provável).
- Padrão 2: Aumento de creatinina com uso de creatina (Exploratório).
</diretriz_executiva>
<estrutura_por_item>
<item>
<padrao_detectado>TSH em ascensão progressiva (13.7 uui/ml) com T4L dentro da referência (1.39 ng/dl).</padrao_detectado>
<trajetoria_projetada>Possível progressão para hipotireoidismo clínico se não houver intervenção ou controle da causa base.</trajetoria_projetada>
</item>
</estrutura_por_item>
</analise_de_padroes_latentes>

<end>

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 1 - Dr. Próximo-Passo
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 28,834 in / 1,432 out
Custo estimado: US$ 0.002592

<start>
<exames_recomendados>
   <item>
      <exame>TSH (Hormônio Tireoestimulante) + T4 Livre</exame>
      <area>laboratorial</area>
      <prioridade>alta</prioridade>
      <funcao_no_debate>confirmar leitura atual</funcao_no_debate>
      <momento_reavaliacao>4 semanas</momento_reavaliacao>
      <justificativa>Confirmação da disfunção tireoidiana (TSH 13.70) e exclusão de erro laboratorial ou flutuação transitória.</justificativa>
   </item>
   <item>
      <exame>Creatinina + eGFR (TFGe)</exame>
      <area>laboratorial</area>
      <prioridade>alta</prioridade>
      <funcao_no_debate>confirmar leitura atual</funcao_no_debate>
      <momento_reavaliacao>Após 15 dias de suspensão de Creatina</momento_reavaliacao>
      <justificativa>Avaliação da função renal sem o possível efeito de artefato da suplementação de creatina.</justificativa>
   </item>
   <item>
      <exame>Urina Tipo I</exame>
      <area>laboratorial</area>
      <prioridade>alta</prioridade>
      <funcao_no_debate>excluir confundidor relevante</funcao_no_debate>
      <momento_reavaliacao>Coleta junto com a nova creatinina</momento_reavaliacao>
      <justificativa>Triagem inicial de dano estrutural renal (hematúria/proteinúria).</justificativa>
   </item>
   <item>
      <exame>Relação Albumina/Creatinina Urinária</exame>
      <area>laboratorial</area>
      <prioridade>alta</prioridade>
      <funcao_no_debate>excluir confundidor relevante</funcao_no_debate>
      <momento_reavaliacao>Coleta junto com a nova creatinina</momento_reavaliacao>
      <justificativa>Estratificação de risco renal (microalbuminúria).</justificativa>
   </item>
   <item>
      <exame>Anti-TPO (Anticorpos Anti-Peroxidase)</exame>
      <area>laboratorial</area>
      <prioridade>média</prioridade>
      <funcao_no_debate>confirmar mecanismo</funcao_no_debate>
      <momento_reavaliacao>Não definido com os dados atuais</momento_reavaliacao>
      <justificativa>Investigação etiológica de tireoidite autoimune (Hashimoto).</justificativa>
   </item>
</exames_recomendados>

<exames_condicionais>
   <item>
      <exame>Cistatina C</exame>
      <area>laboratorial</area>
      <gatilho>Persistência de eGFR reduzida (abaixo de 60) após suspensão da creatina.</gatilho>
      <relacao_exame_principal>Creatinina/eGFR</relacao_exame_principal>
      <funcao_no_debate>excluir confundidor relevante</funcao_no_debate>
      <momento_reavaliacao>Após reteste da creatinina</momento_reavaliacao>
      <justificativa>Marker de filtração glomerular independente de massa muscular e dieta.</justificativa>
   </item>
</exames_condicionais>

<calculos_sugeridos>
   <item>
      <nome_calculo>Relação TSH/T4L</nome_calculo>
      <dados_necessarios>TSH e T4 Livre recentes</dados_necessarios>
      <motivo_clinico_utilidade>Auxiliar na distinção entre hipotireoidismo subclínico e primário.</motivo_clinico_utilidade>
      <status_dados_disponiveis>Suficientes no CONTEXTO</status_dados_disponiveis>
      <impacto_esperado_incerteza>Refinamento da disfunção tireoidiana.</impacto_esperado_incerteza>
      <status>sugerido, não executado por calculadora determinística</status>
   </item>
</calculos_sugeridos>

<perguntas>
   <item>
      <pergunta>Apenas a título de informação: você tem notado inchaço nas pernas, alteração na cor da urina ou aumento da frequência urinária à noite?</pergunta>
      <prioridade>alta</prioridade>
      <incerteza_que_resolve>Sintomatologia sugestiva de comprometimento renal funcional.</incerteza_que_resolve>
   </item>
   <item>
      <pergunta>Para nos ajudar a entender melhor: você tem sentido mais cansaço, pele seca ou sensação de frio excessivo ultimamente?</pergunta>
      <prioridade>alta</prioridade>
      <incerteza_que_resolve>Sintomatologia clínica compatível com hipotireoidismo.</incerteza_que_resolve>
   </item>
   <item>
      <pergunta>Você utiliza algum medicamento ou suplemento além da creatina que não foi mencionado?</pergunta>
      <prioridade>média</prioridade>
      <incerteza_que_resolve>Identificação de possíveis interferentes laboratoriais ou nefrotóxicos.</incerteza_que_resolve>
   </item>
</perguntas>

<dados_obsoletos>
- Dados de 2016-2022: Considerados obsoletos para a tomada de decisão atual devido ao intervalo de tempo (>12 meses) e ausência de correlação com o quadro agudo de 2026.
</dados_obsoletos>

<tecnologia>
Nenhuma tecnologia adicional prioritária. O foco deve ser a padronização laboratorial e o controle de variáveis (suspensão de suplementos) antes de qualquer investigação avançada.
</tecnologia>
<end>

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 1 - Dr. Challenger
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 28,275 in / 1,037 out
Custo estimado: US$ 0.002432

<start>
<criticas>
  <falhas_criticas>
    <critica nivel="alta">
      A conclusão de "declínio da função renal" baseada em TFGe de 52 mL/min/1,73m² (09/03/2026) e Creatinina de 1,64 mg/dL (09/03/2026) ignora a regra de cautela renal para valores isolados. Embora a creatinina esteja fora da referência, o contexto de uso de Creatina (suplemento) é um confundidor direto. A ausência de Urina Tipo I e RAC quantitativa impede a classificação como "doença renal".
      Correção esperada: Rebaixar a hipótese de "declínio da função renal" para "achado a confirmar (potencial artefato por suplementação)". Exigir obrigatoriamente o pacote: nova creatinina/eGFR após 15 dias sem creatina, Urina Tipo I e RAC.
    </critica>
    <critica nivel="alta">
      A hipótese de "Disfunção do Eixo Tireoidiano" como causa-raiz primária é sustentada por TSH de 13,70 uui/ml (28/02/2026), mas o T4 Livre (1,39 ng/dl, 02/04/2026) está dentro da referência. O uso de "provável" para hipotireoidismo clínico sem anticorpos (Anti-TPO) ou reteste é um overclaim.
      Correção esperada: Rebaixar para "hipótese de disfunção tireoidiana a confirmar". Exigir Anti-TPO e reteste de TSH/T4L para diferenciar de flutuação transitória ou fase inicial de tireoidite.
    </critica>
    <critica nivel="moderada">
      A análise de "Sistema Hematológico" descarta alterações como "pontuais sem âncora", ignorando a queda acentuada de Leucócitos (2540/mm³ em 28/02/2026) e Segmentados (1025/mm³ em 31/01/2026). Embora possam ser ruído, a dismissão sem investigação de causa infecciosa ou medular é prematura.
      Correção esperada: Manter como ponto de monitoramento e solicitar hemograma completo com contagem de reticulócitos se persistir a leucopenia.
    </critica>
  </falhas_criticas>

  <confronto_otimizacao>
    <item>A relação TSH/T4L sugerida como cálculo deve ser tratada com extrema cautela, pois não substitui a avaliação clínica da tireoide e pode induzir a uma falsa sensação de precisão diagnóstica.</item>
    <item>A recomendação de suspensão de creatina é correta, mas deve ser enfatizada como condição *sine qua non* para qualquer conclusão sobre a função renal.</item>
  </confronto_otimizacao>

  <vies>
    <item>Viés de confirmação: O agente focou nos marcadores alterados (TSH, Creatinina) para construir uma narrativa de "doença sistêmica", negligenciando a possibilidade de artefatos laboratoriais por suplementação ou estresse agudo.</item>
    <item>Simplificação excessiva: A tentativa de agrupar o TSH elevado e a creatinina elevada em uma única "patologia sistêmica" sem evidência de conexão fisiopatológica clara.</item>
  </vies>

  <pontos_validados>
    <item>A necessidade de suspensão de creatina por 15 dias é validada e essencial para a integridade da reavaliação renal. (Evidência: Creatinina 1,64 mg/dL em 09/03/2026).</item>
    <item>A solicitação de Urina Tipo I e RAC é validada como passo obrigatório para estratificação de risco renal. (Evidência: TFGe 52 ml/min/1,73m² em 09/03/2026).</item>
    <item>A necessidade de reteste de TSH e T4L é validada para confirmar a persistência da alteração tireoidiana. (Evidência: TSH 13,70 uui/ml em 28/02/2026).</item>
  </pontos_validados>
</criticas>
<end>

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 1 - Dr. Auditor
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 32,449 in / 1,484 out
Custo estimado: US$ 0.002879

<start>

<analise_conflito>
A análise dos agentes anteriores apresenta divergências na interpretação da gravidade dos eixos tireoidiano e renal. O Dr. Challenger corretamente apontou que a classificação de "doença renal" e "hipotireoidismo clínico" carece de confirmação estrutural. 
1. **Eixo Renal:** A elevação da Creatinina (1.64 mg/dL) e redução da TFGe (52 ml/min/1,73m²) ocorrem em contexto de uso de creatina. A Cistatina C (0.87 mg/L) está dentro da referência, o que sugere que o declínio da TFGe pode ser um artefato laboratorial (interferência da creatina na creatinina sérica). A crítica do Challenger sobre a necessidade de Urina Tipo I e RAC é validada.
2. **Eixo Tireoidiano:** O TSH (13.70 uui/ml) está elevado, mas o T4 Livre (1.39 ng/dl) permanece dentro da referência. Isso caracteriza um hipotireoidismo subclínico, não clínico. A ausência de Anti-TPO impede a confirmação de tireoidite autoimune.
3. **Sistema Hematológico:** A queda de leucócitos (2540/mm³) em 28/02/2026 foi um evento pontual, com normalização posterior (6160/ul em 02/04/2026), corroborando a natureza transitória/ruído.
4. **Resolução de Críticas:**
   - Crítica renal (Alta): Parcialmente resolvida. A hipótese de declínio renal foi rebaixada para "hipótese de artefato por suplementação".
   - Crítica tireoidiana (Alta): Resolvida. Reclassificado para "hipotireoidismo subclínico a confirmar".
   - Crítica hematológica (Moderada): Resolvida. A normalização laboratorial recente refuta a necessidade de investigação medular imediata.
</analise_conflito>

<pontos_validados>
1. **Artefato Renal:** A creatinina sérica está sob suspeita de interferência por suplementação de creatina; Cistatina C normal (0.87 mg/L) corrobora a hipótese de artefato.
2. **Hipotireoidismo Subclínico:** TSH elevado com T4L normal define o quadro atual, exigindo confirmação de persistência.
3. **Normalização Hematológica:** A leucopenia observada em fevereiro foi transitória e não sustenta patologia medular.
4. **Protocolo de Investigação:** A necessidade de Urina Tipo I e RAC é mandatória para descartar nefropatia estrutural.
</pontos_validados>

<hipoteses_priorizadas>
1. **Hipotireoidismo Subclínico:** Disfunção tireoidiana com TSH elevado e T4L preservado.
2. **Artefato Laboratorial Renal:** Elevação de creatinina secundária ao uso de creatina, com função renal real preservada (Cistatina C normal).
3. **Disfunção Androgênica:** Aumento expressivo da testosterona total (857 ng/dl) sem causa clara, possivelmente associado a modulação exógena.
</hipoteses_priorizadas>

<nivel_certeza_por_hipotese>
1. **Hipotireoidismo Subclínico:** provável. (TSH 13.70 uui/ml, 28/02/2026; T4L 1.39 ng/dl, 02/04/2026). Necessita reteste para confirmar persistência.
2. **Artefato Laboratorial Renal:** provável. (Creatinina 1.64 mg/dl, 09/03/2026; Cistatina C 0.87 mg/L, 20/03/2026). Necessita suspensão de creatina e reteste.
3. **Disfunção Androgênica:** hipótese. (Testosterona 857 ng/dl, 09/03/2026). Necessita investigação de uso de moduladores.
</nivel_certeza_por_hipotese>

<incertezas_chave>
- Ausência de Anti-TPO para confirmar autoimunidade tireoidiana.
- Ausência de Urina Tipo I e RAC quantitativa para descartar dano renal estrutural.
- Falta de confirmação sobre o uso de outros suplementos ou moduladores hormonais (lacuna de contexto).
</incertezas_chave>

<dados_que_aumentam_certeza>
1. **TSH + T4 Livre:** Confirmar persistência da alteração tireoidiana.
2. **Urina Tipo I + RAC:** Excluir proteinúria/hematúria.
3. **Creatinina + eGFR (após 15 dias sem creatina):** Validar função renal real.
4. **Anti-TPO:** Investigar etiologia autoimune da tireoide.
5. **Anamnese sobre uso de moduladores:** Esclarecer a elevação da testosterona.
</dados_que_aumentam_certeza>

<justificativa_certeza>
1. **Coerência Clínica (25/35):** As hipóteses explicam os marcadores, mas a falta de sintomas relatados pelo paciente limita a correlação clínica.
2. **Suporte Laboratorial (25/35):** Marcadores âncora presentes, mas com forte suspeita de interferência (creatina) e necessidade de reteste (TSH).
3. **Consenso e Resolução (20/20):** Críticas do Challenger foram integralmente incorporadas e as hipóteses reajustadas.
4. **Penalidades (-11):** -5 (exames alta prioridade pendentes: Urina I, RAC, TSH/T4L, Creatinina), -6 (perguntas de alta prioridade não respondidas: sintomas renais e tireoidianos).
**Score Final:** (25+25+20) - 11 = 59%
</justificativa_certeza>

<modo_de_entrega_narrativa>
guiado por investigação
</modo_de_entrega_narrativa>

<certeza>59%</certeza>

<end>

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 2 - Dr. Plano-Ação
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 45,489 in / 1,959 out
Custo estimado: US$ 0.003999

Relatório Integrativo

Nome: Mario Gorini
Idade: 45 anos
Gênero: Homem
Data: 09/06/2026
Laboratório: LAB - LABORATORIO DE PATOLOGIA E CITOLOGIA APLICADA LTDA, DASA
Abertura: Este relatório traduz os dados dos seus exames em uma narrativa clara sobre como seu corpo está funcionando e quais ajustes podem ajudar você a alcançar um estado de maior equilíbrio.

1.2 Objetivo
O objetivo deste relatório é investigar a elevação recente de marcadores da tireoide e dos rins, esclarecendo se estas alterações refletem uma necessidade real de suporte ou se são reflexos de fatores externos, como o uso de suplementos.

1.3 Panorama integrador
Seu corpo está comunicando sinais importantes que merecem atenção organizada. Antes de olharmos os pontos de atenção, é importante reconhecer o progresso que seus exames mostram:
• Vitamina D: subiu de 33 para 68 ng/mL — agora dentro do alvo funcional.
• Vitamina B12: subiu de 392 para 720 pg/mL — uma melhora importante para o metabolismo celular.
• Homocisteína: reduziu de 33.0 para 7.4 µmol/L — um excelente ajuste para a saúde cardiovascular.

Os dados atuais mostram que seu corpo responde bem a ajustes, mas há pontos que precisam de confirmação: a elevação do TSH (hormônio que estimula a tireoide) e a alteração na creatinina (marcador da função renal). É fundamental confirmar se essas mudanças são persistentes ou se foram influenciadas por fatores como o uso de creatina ou flutuações temporárias. A análise atual ainda apresenta incertezas relevantes — os pontos abaixo devem ser validados com exames complementares e acompanhamento profissional.

1.4 Sinais de atenção
Legenda: Alguns marcadores em seus exames indicam áreas que necessitam de acompanhamento para otimizar sua qualidade de vida.
TSH — 13.70 mUI/L | ref 0.4–4.0 | ideal 1.0–2.5 | status: Alto
Creatinina — 1.64 mg/dL | ref 0.7–1.3 | ideal 0.7–0.9 | status: Alto
Relação Albumina/Creatinina — < 30 mg/g | ref < 30.0 | ideal 0.0–10.0 | status: Atenção

1.5 Pontos positivos
Legenda: Marcadores em alvo funcional.
Dica: estes marcadores representam a "vitrine de estabilidade" do organismo.
Cistatina C (soro) — 0.87 mg/L (coletado em 20/03/2026) | ref 0.56–0.99 | status: Ok

1.6 Conceitos-chave
TSH (Hormônio Tireoestimulante): 13.70 mUI/L | ref 0.4–4.0 | ideal 1.0–2.5. Este hormônio é o "mensageiro" que estimula a tireoide. Quando está acima do alvo, indica que o corpo está pedindo mais suporte para a tireoide funcionar.
Creatinina: 1.64 mg/dL | ref 0.7–1.3 | ideal 0.7–0.9. É um marcador de como seus rins filtram o sangue. Como você utiliza creatina, este valor pode estar artificialmente elevado, o que precisa ser checado.
Testosterona Total: 857 ng/dL | ref 250–836. Nível de hormônio masculino que está acima da referência, o que merece avaliação para entender se é uma produção natural ou influência de fatores externos.

1.7 Distribuição dos exames
Seus exames cobrem eixos hormonais, renais e metabólicos. A maioria dos marcadores está estável, com exceção dos pontos de atenção citados, que concentram a necessidade de investigação.

Parte 2 — Causas raiz priorizadas

2. Causas raiz priorizadas

1. Equilíbrio da tireoide — Oportunidade de cuidado
O TSH elevado sugere que a tireoide pode precisar de mais suporte. Como o T4 Livre (hormônio ativo) está dentro da referência, trata-se de um ajuste inicial. Precisamos confirmar se isso é uma tendência ou uma flutuação.
Perguntas para sua reflexão: Você tem sentido mais cansaço, pele seca ou sensação de frio excessivo ultimamente?

2. Saúde dos rins — Ponto de atenção
A creatinina está acima do ideal, mas a Cistatina C (um marcador mais preciso e menos influenciado por massa muscular ou suplementos) está normal. Isso sugere que a função renal pode estar preservada e a alteração ser um reflexo do uso de creatina.
Perguntas para sua reflexão: Você tem notado inchaço nas pernas, alteração na cor da urina ou aumento da frequência urinária à noite?

Quando conectamos esses pontos, vemos que seu organismo está em um momento de transição que exige clareza antes de qualquer intervenção medicamentosa.

Parte 3 — Plano de ação estratégico

3.1 Objetivo central
Estabilizar os marcadores de tireoide e rins através da confirmação laboratorial e controle de variáveis (suspensão de suplementos), garantindo que qualquer ação futura seja baseada em dados reais.

3.2 Fase 1 | 30 dias para melhoria
Pilar: Organização metabólica e hidratação.
O que fazer: Suspender o uso de creatina por 15 dias antes de repetir os exames renais. Manter hidratação constante (cerca de 35ml de água por kg de peso).
Por que isso impacta múltiplos sistemas: A suspensão da creatina permite uma leitura real da função renal. A hidratação adequada melhora a filtração renal e o suporte metabólico geral.

3.3 Estratégias de Nutrição
A meta é reduzir a sobrecarga sobre os rins e apoiar a tireoide.
Priorizar: Alimentos naturais, vegetais frescos e proteínas de fácil digestão.
Reduzir: Excesso de sódio e alimentos ultraprocessados, que sobrecarregam a filtração renal.
A estratégia nutricional visa dar ao corpo o ambiente necessário para que os exames de reavaliação reflitam seu estado real.

3.4 Suplementação
A) Sugestões de uso livre (FASE 1)
Neste momento, não há suplementos de uso livre indicados. O foco é a suspensão de substâncias para reavaliação.

B) Sugestões para avaliar com profissional
- Creatina: Suspender por 15 dias para reteste da função renal. Validar com seu médico a necessidade de retomada após a normalização dos exames.

3.5 Fase 2 | Otimização progressiva
A Fase 2 será construída após a resposta à Fase 1 e à reavaliação laboratorial indicada.

3.6 Avaliação profissional
Especialidade: Endocrinologia e Nefrologia (apenas se os exames de confirmação persistirem alterados).
Motivo: Investigação de hipotireoidismo subclínico e estratificação de risco renal.
Urgência: Acompanhamento.
Neste momento, os dados não indicam necessidade de avaliação especializada adicional antes da rechecagem dos exames.

Parte 4 — Monitoramento

4. Monitoramento
| Posição | Exame | Objetivo clínico | Causa-raiz relacionada | Prazo |
| 1 | TSH + T4 Livre | Confirmar tireoide | Tireoide | 4 semanas |
| 2 | Creatinina + eGFR | Confirmar função renal | Rins | 15 dias após suspender creatina |
| 3 | Urina Tipo I + RAC | Excluir dano estrutural | Rins | Junto com creatinina |
| 4 | Anti-TPO | Investigar autoimunidade | Tireoide | Junto com TSH |

4.2 Exames considerados, mas não priorizados agora
- Cistatina C: Não priorizado pois já está dentro da referência e serve como dado de segurança.

Visão futura
Com os ajustes de rotina e a reavaliação dos exames, teremos uma fotografia muito mais clara do seu estado de saúde. O foco agora é confirmar se os sinais de atenção são transitórios. Ao estabilizar esses pontos, você terá a segurança necessária para seguir com seus objetivos de saúde.

Este relatório é uma ferramenta educativa e preventiva, não substitui uma consulta médica nem define um diagnóstico. Discuta todas as recomendações com seu profissional de saúde antes de implementá-las.

──────────────────────────────────────────────────────────────────────────
🔹 RODADA 2 - Médico Assistente
──────────────────────────────────────────────────────────────────────────
Confiança: 0%
Tokens: 33,654 in / 1,974 out
Custo estimado: US$ 0.003116

*Este relatório é um instrumento automatizado de apoio à decisão clínica, gerado por análise computacional de dados laboratoriais (Sistema ORIA). Não constitui diagnóstico médico, laudo ou prescrição. Todos os achados devem ser interpretados e validados pelo médico assistente à luz do quadro clínico completo do paciente.*

# RELATÓRIO CLÍNICO DE APOIO AO MÉDICO

## 1. Resumo executivo

### 1.1 Síntese rápida
- Achados compatíveis com hipotireoidismo subclínico e possível artefato renal por suplementação. Score do Auditor: 59%.
- TSH: 13,70 uui/ml (28/02/2026); Creatinina: 1,64 mg/dl (09/03/2026); TFGe: 52 ml/min/1,73m² (09/03/2026).
- Lacuna: Necessidade de Urina Tipo I, RAC e reteste de TSH/Creatinina após suspensão de creatina.

### 1.2 Resumo detalhado
O paciente apresenta elevação de TSH com T4 Livre dentro da referência, compatível com hipotireoidismo subclínico. Observa-se elevação da creatinina e redução da TFGe, porém com Cistatina C normal, sugerindo possível interferência do uso de creatina. O perfil androgênico mostra elevação da testosterona total. A leucopenia observada em fevereiro foi transitória e não se sustenta como achado atual. O score de confiança do Auditor é de 59%, limitado pela ausência de exames confirmatórios (Urina I, RAC, Anti-TPO) e pela necessidade de reteste após suspensão de suplementos. A prioridade clínica imediata é a exclusão de artefatos laboratoriais e a estratificação de risco renal.

## 2. Principais alterações objetivas

### 2.1 Eixo Tireoidiano
- Classificação no debate: provável
- Grau de confiança prático: moderado
- Impacto clínico prático: relevante
- Implicação clínica imediata: sugere investigação ativa
- Status clínico: alteração leve sem diagnóstico
- Manifestação clínica/laboratorial objetiva: TSH elevado com T4 Livre dentro da referência.
- Etiologia ou causa de base: não definida
- Base objetiva:
  - TSH — 13,70 uui/ml (28/02/2026) | Referência padrão: 0,4-4,0 | Tendência: ↗ subindo leve
  - T4 LIVRE — 1,39 ng/dl (02/04/2026) | Referência padrão: 0,8-1,9 | Tendência: ↗ subindo leve
- Longitudinal: [1] Cluster Eixo Hormonal e Tireoidiano. TSH com alta recente e T4L estável.
- Trajetória observada vs prognóstico: prognóstico não estabelecido pelos dados atuais.
- Recomendação de confirmação: Reteste de TSH e T4 Livre em 4 semanas; solicitação de Anti-TPO.
- Leitura clínica: Hipotireoidismo subclínico a confirmar.

### 2.2 Saúde Renal
- Classificação no debate: provável
- Grau de confiança prático: moderado
- Impacto clínico prático: relevante
- Implicação clínica imediata: sugere investigação ativa
- Status clínico: alteração leve sem diagnóstico
- Manifestação clínica/laboratorial objetiva: Creatinina elevada e TFGe reduzida, com Cistatina C normal.
- Etiologia ou causa de base: parcialmente definida (possível artefato por creatina)
- Base objetiva:
  - CREATININA — 1,64 mg/dl (09/03/2026) | Referência padrão: 0,7-1,3 | Tendência: ↑ subindo
  - ESTIMATIVA DA TAXA DE FILTRAÇÃO GLOMERULAR — 52 ml/min/1,73m² (09/03/2026) | Referência padrão: >60 | Tendência: ↓ descendo
- Longitudinal: [1] Cluster Saúde Renal. Creatinina em ascensão recente; Cistatina C (0,87 mg/L) dentro da referência.
- Trajetória observada vs prognóstico: prognóstico não estabelecido pelos dados atuais.
- Recomendação de confirmação: Suspensão de creatina por 15 dias, seguida de novo teste de creatinina, TFGe, Urina Tipo I e RAC.
- Leitura clínica: Achado sugestivo de artefato laboratorial por suplementação; Cistatina C normal sugere filtração glomerular preservada.

### 2.3 Eixo Androgênico
- Classificação no debate: hipótese
- Grau de confiança prático: baixo
- Impacto clínico prático: moderado
- Implicação clínica imediata: sugere acompanhamento
- Status clínico: alteração leve sem diagnóstico
- Manifestação clínica/laboratorial objetiva: Testosterona total elevada.
- Etiologia ou causa de base: não definida
- Base objetiva:
  - TESTOSTERONA TOTAL — 857,00 ng/dl (09/03/2026) | Referência padrão: 240-816 | Tendência: ↑ subindo
- Longitudinal: [1] Cluster Eixo Hormonal e Tireoidiano. Aumento expressivo em relação ao histórico.
- Trajetória observada vs prognóstico: prognóstico não estabelecido pelos dados atuais.
- Recomendação de confirmação: Anamnese sobre uso de moduladores hormonais ou suplementos.
- Leitura clínica: Elevação isolada de testosterona total sem causa definida no momento.

## 3. Achados complementares fora do alvo funcional, mas com menor peso clínico convencional
- Relação Albumina/Creatinina — <30 mg/g (dentro da referência padrão, porém acima do alvo funcional ideal).

## 5. Pontos de dúvida e limitações relevantes
- Lacunas de contexto: Uso de moduladores hormonais ou outros suplementos não declarados.
- Limitações longitudinais: A comparação de creatinina está limitada pelo uso de suplementação (creatina) que altera a cinética do marcador.

## 7. Pontos que merecem maior atenção do médico
- TSH elevado (13,70 uui/ml) — Necessita reteste para confirmar hipotireoidismo subclínico.
- Creatinina elevada (1,64 mg/dl) — Necessita reteste após suspensão de creatina.
- TFGe reduzida (52 ml/min/1,73m²) — Necessita Urina Tipo I e RAC para exclusão de dano estrutural.

## 9. Dados que mais aumentariam a certeza clínica

| Prioridade | Dado ou exame | Para esclarecer o quê | Impacto esperado |
|---|---|---|---|
| 1 | TSH + T4 Livre | Confirmar persistência da disfunção tireoidiana | Alta |
| 2 | Urina Tipo I + RAC | Excluir dano estrutural renal | Alta |
| 3 | Creatinina + eGFR | Validar função renal real (pós-suspensão de creatina) | Alta |
| 4 | Anti-TPO | Investigar etiologia autoimune tireoidiana | Moderado |

## 11. Síntese final para decisão clínica
Os achados laboratoriais apontam para um quadro de hipotireoidismo subclínico e uma possível elevação artificial da creatinina sérica secundária ao uso de creatina. A função renal real parece preservada, dado o valor normal de Cistatina C.

A validação clínica requer a confirmação da persistência das alterações laboratoriais após a suspensão de suplementos e a realização de exames de triagem renal estrutural (Urina I e RAC).

**Plano de confirmação e acompanhamento:**
- Incerteza principal: Persistência do hipotireoidismo e real função renal.
- Dado/exame/pergunta que resolve: Reteste de TSH/T4L, Creatinina/eGFR (após 15 dias sem creatina), Urina I e RAC.
- Momento ou condição de reavaliação: 4 semanas.
- Impacto esperado na decisão clínica: Definição de necessidade de reposição hormonal e exclusão de nefropatia.

*Este relatório é um instrumento automatizado de apoio à decisão clínica, gerado por análise computacional de dados laboratoriais (Sistema ORIA). Não constitui diagnóstico médico, laudo ou prescrição. Todos os achados devem ser interpretados e validados pelo médico assistente à luz do quadro clínico completo do paciente.*

================================================================================
💰 RESUMO DE CUSTOS
================================================================================
Custo Total Estimado: US$ 0.018358

